services:
  
  postgres:
    container_name: my_database
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=projects'
      - 'POSTGRES_USER=project'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - './Project/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql'
    restart: 'always'


  backend:
    build: ./Project/
    container_name: backend
    ports:
      - '8081:8081'
    environment:
      db-url: 'jdbc:postgresql://postgres:5432/projects'
      db-username: 'project'
      db-password: 'secret'
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://backend:8081/actuator/health | grep UP || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      - 'postgres'

  counter:
    build: ./Counter-Service/
    container_name: counter
    ports:
      - '8082:8082'
    depends_on:
      backend:
        condition: service_healthy
  
