services:
  
  postgres:
    container_name: my_database
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=projects'
      - 'POSTGRES_USER=project'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - './Project/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql'
    restart: 'always'


  backend:
    build: ./Project/
    container_name: backend
    ports:
      - '8081:8081'
    environment:
      db-url: 'jdbc:postgresql://postgres:5432/projects'
      db-username: 'project'
      db-password: 'secret'
    restart: always
    depends_on:
      - 'postgres'

  counter:
    build: ./Counter-Service/
    container_name: counter
    #environment:
      #OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318' es it schon in der application properties
    ports:
      - '8082:8082'
    restart: always
    depends_on:
      backend:
        condition: service_started


  
